/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pertemuan10;


import javax.swing.*; // Mengimpor pustaka Swing untuk membuat komponen GUI seperti JFrame, JPanel, JLabel, dll.
import java.awt.event.MouseAdapter; // Mengimpor kelas untuk menangani event mouse.
import java.awt.event.MouseEvent; // Mengimpor kelas untuk representasi event mouse.

/**
 *
 * @author afifa
 */
//Kelas register untuk menangani proses registrasi pengguna.
public class register extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public register() {
        initComponents(); // Memanggil metode untuk inisialisasi komponen GUI.
        addloginClickListener(); // Menambahkan event listener untuk label login.
        pack(); // Menyusun ukuran jendela agar sesuai dengan komponen di dalamnya.
        setLocationRelativeTo(null); // menempatkan tampilan di tengah layar                                                                                        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usernameTF = new javax.swing.JTextField();
        registerBTN = new javax.swing.JButton();
        passwordTF = new javax.swing.JPasswordField();
        confirmPwTF = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        loginLB = new javax.swing.JLabel();
        lihatPassCB = new javax.swing.JCheckBox();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Kalkulator");
        setAlwaysOnTop(true);

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));
        jPanel2.setPreferredSize(new java.awt.Dimension(737, 440));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("REGISTER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 27)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 27)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");

        usernameTF.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N

        registerBTN.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        registerBTN.setForeground(new java.awt.Color(255, 51, 51));
        registerBTN.setText("Register");
        registerBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBTNActionPerformed(evt);
            }
        });

        passwordTF.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        passwordTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTFActionPerformed(evt);
            }
        });

        confirmPwTF.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        confirmPwTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPwTFActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 27)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Confirm Password");

        loginLB.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        loginLB.setForeground(new java.awt.Color(255, 255, 255));
        loginLB.setText("Sudah memiliki akun? Login disini");

        lihatPassCB.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        lihatPassCB.setForeground(new java.awt.Color(255, 255, 255));
        lihatPassCB.setText("Lihat Password");
        lihatPassCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatPassCBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(registerBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lihatPassCB))
                    .addComponent(usernameTF)
                    .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmPwTF, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(loginLB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(confirmPwTF, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lihatPassCB)
                .addGap(3, 3, 3)
                .addComponent(registerBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginLB)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     // Metode yang dipanggil saat tombol register diklik
    private void registerBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBTNActionPerformed
        // Mengambil input dari pengguna
        String username = usernameTF.getText();
        String password = new String(passwordTF.getPassword());
        String confirmPW = new String(confirmPwTF.getPassword());

        // Validasi jika password atau konfirmasi password kosong
        if (username.isEmpty() && password.isEmpty() && confirmPW.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Masukkan Username dan Password untuk registrasi."); //akan muncul pesan peringatan ini
        return; // Hentikan proses jika validasi gagal
        }
        
        // Validasi jika password atau konfirmasi password kosong
        if (password.isEmpty() || confirmPW.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Password dan konfirmasi password tidak boleh kosong."); //akan muncul pesan peringatan ini
        return; // Hentikan proses jika validasi gagal
        }
        
        // Validasi input jika username yang dibuat hanya 6 karakter
        if (username.length() <= 6) {
            JOptionPane.showMessageDialog(this, "Username harus lebih dari 6 karakter."); //akan muncul pesan peringatan ini
            return; // Hentikan proses jika validasi gagal
        }

        //apabila password tidak sesuai dengan konfirmasi password
        if (!password.equals(confirmPW)) {
            JOptionPane.showMessageDialog(this, "Password dan konfirmasi password tidak sesuai."); //akan muncul pesan peringatan ini
            return; // Hentikan proses jika validasi gagal
        }

        // Jika semua validasi berhasil, lanjutkan dengan registrasi
        if (MyJDBC.register(username, password)) {
            this.dispose(); // Menutup jendela register saat registrasi berhasil
            login login = new login();
            JOptionPane.showMessageDialog(login, "Registrasi akun berhasil!");
            login.setVisible(true); // Menampilkan jendela login
        } else { //kondisi yang akan dijalankan apabila username sudah ada dalam database
            JOptionPane.showMessageDialog(this, "Registrasi akun gagal! \nUsername telah terdaftar silahkan buat dengan username baru");
        }
    }//GEN-LAST:event_registerBTNActionPerformed

    private void addloginClickListener(){
        // Menambahkan listener mouse ke komponen `loginLB`.
        loginLB.addMouseListener(new MouseAdapter(){
            public void mouseClicked(MouseEvent e){
                register.this.dispose(); // Menutup form registrasi saat komponen diklik.
                
                new login().setVisible(true);  // Membuka form login baru.
            }
        });
    }
    
     private boolean validasiUserInput(String username, String password, String confirmPass){
        // Memeriksa apakah username, password, atau konfirmasi password kosong.
        if(username.length() == 0 || password.length() == 0 || confirmPass.length() == 0) return false;
        // Memeriksa apakah panjang username kurang dari 6 karakter.
        if(username.length() < 6) return false;
        // Memeriksa apakah password dan konfirmasi password tidak cocok.
        if(!password.equals(confirmPass)) return false;
        // Jika semua validasi lulus, kembalikan true.
        return true;
    }

    

    
    private void passwordTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTFActionPerformed

    private void confirmPwTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPwTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPwTFActionPerformed

    private void lihatPassCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatPassCBActionPerformed
        // Jika checkbox `lihatPassCB` dipilih, tampilkan teks password dan konfirmasi password.
        if(lihatPassCB.isSelected()){
            confirmPwTF.setEchoChar((char)0); // Menampilkan teks secara jelas.
            passwordTF.setEchoChar((char)0); // Menampilkan teks secara jelas.
        }else{ // Mengembalikan teks ke mode password (disamarkan).
           confirmPwTF.setEchoChar('*');
           passwordTF.setEchoChar('*'); 
        }
    }//GEN-LAST:event_lihatPassCBActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmPwTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JCheckBox lihatPassCB;
    private javax.swing.JLabel loginLB;
    private javax.swing.JPasswordField passwordTF;
    private javax.swing.JButton registerBTN;
    private javax.swing.JTextField usernameTF;
    // End of variables declaration//GEN-END:variables
}
